language: python
python:
  - 2.7
  - 3.4
matrix:
  allow_failures:
    - python: 3.4
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
before_install:
  - pip install codecov
after_success:
  - codecov